server:
  port: 8081

spring:
  application:
    name: user-registration-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/User-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

  jackson:
    deserialization:
      fail-on-unknown-properties: true

wallet:
  service:
    base-url: ${WALLET_SERVICE_BASE_URL:http://localhost:8082}

jwt:
  secret-base64: ${JWT_SECRET_BASE64:"lf8pg3dCyON+2Zv7t98MZ42yh2xaXOUYL+YqLjcx+sg="}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  issuer: ${JWT_ISSUER:payment-user-service}
  audience: ${JWT_AUDIENCE:payment-platform}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
app:
  admin:
    email: ${ADMIN_EMAIL:admin@payment.com}
    password: ${ADMIN_PASSWORD:admin@payment.com}		
